### ISSUE TITLE
Infidel bricks

### ISSUE THREAD

**Issue by savetz** [DeMille/encrusted#7]
After removing/re-inserting some bricks in Infidel, the description of the panel gets screwy.
<img width="623" alt="screenshot 2018-10-05 at 6 50 28 pm" src="https://user-images.githubusercontent.com/15160098/46566281-65b65100-c8d0-11e8-8ed8-113878239644.png">

**Comment by DeMille** [comment]
This one has been driving me nuts! I've been able to reproduce the same issue in the desert (didn't get to the bricks yet). It's not a string decoding issue unfortunately, something goes wrong before that.

It breaks here because the game is trying to read a string from address 0, which would never be right. I've tried to work my way backwards to see where the logic breaks down but I haven't been able to figure out which instruction that would be. My guess is that there is some edge case in the documentation that I've overlooked that's messing with the math.

**Comment by DeMille** [comment]
As an update to this, I was able to reproduce the **exact** same issue as above (in the desert, not the bricks) in [Frotz](http://www.davidkinder.co.uk/frotz.html) (which seems like a pretty serious interpreter). Between this and the different test suites that are now passing, I'm inclined to think it's a error in the game itself? For now I think I'll do some housekeeping, and come back to this if a similar issue pops up elsewhere.
